name: presentation
description: Set of tools providing presentation capabilities (tansitions, animation, navigation,...) to a Flutter application
version: 0.0.7
author: Tomek Pola≈Ñski <polanski.tomek@gmail.com>
homepage: https://github.com/tomaszpolanski/presentation

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

